### ISSUE TITLE
[PE-D] List command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W08-2/tp#208]
when I type "list blah blah" it should return something as unknown command but instead it is listing all the commands. I think this needs to be rectified. 
Perhaps something like the right command format can be displayed so that the user can enter the correct command

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: naranghardik16/ped#3

**Comment by ganhongyao** [comment]
![image](https://user-images.githubusercontent.com/75519136/139520079-1f73a567-99db-4e9d-8258-ec4a7c556e99.png)

This is the expected behaviour, as seen in the UG. Thanks for the feedback anyways.
