### ISSUE TITLE
[PE-D] Bugs on `show` command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W08-2/tp#211]
The file is successfully saved with

![image.png](https://raw.githubusercontent.com/eltonyeh/ped/main/files/6231ecb9-c375-4ced-9beb-4b53e85b3a69.png)

but fails with

![image.png](https://raw.githubusercontent.com/eltonyeh/ped/main/files/dcff432b-a79a-4d84-a2dc-b12f65a4afaa.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: eltonyeh/ped#7

**Comment by jonas-chow** [comment]
Seems like I didn't add a check to check if the directory exists and make the directory if it didn't
