### ISSUE TITLE
[PE-D] Alias does not work properly when add is aliased

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W08-2/tp#213]
![image.png](https://raw.githubusercontent.com/Gabau/ped/main/files/0104bdb6-2c78-49d4-a223-1ad312570437.png)

Bug occurs when add is aliased into another command.

Run the following commands in sequence to replicate.

```
alias -c exit -as add
alias -c add student -as car
```

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Gabau/ped#2

**Comment by jonas-chow** [comment]
Definitely a big problem. I'll have to think about how I want to handle this...
