### ISSUE TITLE
[PE-D] Bugs on `import`

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W08-2/tp#218]
![image.png](https://raw.githubusercontent.com/eltonyeh/ped/main/files/56fedd6b-5bef-41d5-9c34-358da45b07bb.png)

The message returned by the app does not match the actual error. It should return something about the wrong file extension.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: eltonyeh/ped#10

**Comment by jonas-chow** [comment]
Unable to reproduce this error.
Seems like user might have tried to import from an actual png file and the read function read the pixels or something.
Will add a check that the file name ends with `.csv`

**Comment by jonas-chow** [comment]
Also, this behaviour does technically allow for someone to rename their .csv file with a .png extension, and import it with no errors.
Which is... probably not desirable I guess....
