### ISSUE TITLE
[PE-D] Show command does not work if involving assessment with non-percentage score

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W08-2/tp#224]
![image.png](https://raw.githubusercontent.com/jyrw/ped/main/files/49954bd6-4c1a-4484-87c8-cc0c8ca50720.png)

Pressing enter on the above screen does not do anything: the text input does not turn red and the command box is not cleared. No error message is provided. 

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: jyrw/ped#8

**Comment by zhing22** [comment]
its because i fixed the axis to only display 0 too 100, so out of bound scores disappoeared, shoudbt be a problem after we fix the score regex issue

**Comment by nbvannhi** [comment]
Will be resolved in #221
