### ISSUE TITLE
[PE-D] optional -t command not working as specified in import command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W08-2/tp#227]
#### Import command specified in UG: 

import -f &lt;file_path&gt; [-g &lt;number_of_group_columns&gt;] [-a &lt;number_of_assessment_columns&gt;] [-t &lt;number_of_tag_columns&gt;]

#### Import command specified during testing: 

`import -f C:\Users\SourceControl\sourceControl.csv -t 1`

#### Expected output:
Students imported with `beginner`/`intermediate`/`advanced` tags.

#### Actual output:

![image.png](https://raw.githubusercontent.com/Jacobnbh/ped/main/files/4b4765a5-e638-4af0-8d93-a5397c8f0773.png)

Student's groups have been converted to tags

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Jacobnbh/ped#2

**Comment by jonas-chow** [comment]
I think the import format is just too confusing lol...
Might end up using the headers after all.

Perhaps:
name column header should start with -n
id column header should start with -i
group column header should start with -g
assessment column header should start with -a
tag column header should start with -t
