### ISSUE TITLE
[PE-D] Typo found in 4th bullet point of the `alias` command format description

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W08-2/tp#228]
### Typo found:
* Default and existing aliases can still be used after new alias is added. e.g. after alias -c add student **-a** as, both as and add student can be used.

### Suggested fix:
* Default and existing aliases can still be used after new alias is added. e.g. after alias -c add student **-as** as, both as and add student can be used.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Jacobnbh/ped#3

**Comment by zhing22** [comment]
resloved
