### ISSUE TITLE
[PE-D] Making bytecode executable in Linux

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W08-2/tp#232]
In an OS based off of Linux, it might be necessary to run `chmod +x sourceControl.jar`,
It might be better to mention so in the quick start.

If `chmod` is not run, double clicking may not work.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Gabau/ped#4

**Comment by zhing22** [comment]
resloved
