### ISSUE TITLE
Add test cases

### ISSUE THREAD

**Issue by zhing22** [AY2122S1-CS2103T-W08-2/tp#247]
chart:
- [x] commons/util/chartutil

command: 
- [x]         command/showCommand
- [x]         command/commandResult
- [x]         parser/showCommandParser (one function not tested)

student (just some functions missing):
- [x]         student/assessment
- [x]          student/name 
- [x]  student/score 
- [x]  student/student 
- [x]  student/uniqueStudentList(hashcode)
- [x]  student/tag
- [x]  student/nameEqualsPredicate

student lists (some functions missing):
- [x]         student/assessmentlist
- [x]  student/grouplist

chart analysis: 
- [x] student/assessmentStatistics - @ganhongyao 
- [x]        student/group + studentStatistics

model: 
- [x]         model/util/addressbook
- [x]         model/util/modelmanager
- [x]         model/util/userPref(hashcode)

i'm not sure if testable:
- [x] logic/logicManager

**Comment by jonas-chow** [comment]
I'll handle LogicManager and the non-student model tests.
See #257

**Comment by nbvannhi** [comment]
@zhing22 I think showCommand and showCommandParser haven't been tested? Since actually I'm still working on it ;-;

**Comment by leonghongfai** [comment]
@nbvannhi I finished some of showCommand already, but mostly missing the execute success cases. Can you add on from there?

**Comment by nbvannhi** [comment]
I will do
- student/assessment
- student/assessmentlist
- student/score

**Comment by nbvannhi** [comment]
> 
> 
> @nbvannhi I finished some of showCommand already, but mostly missing the execute success cases. Can you add on from there?

Hmm I just take a look at your PR and actually I have the same problem with testing charts. Perhaps @ganhongyao or @zhing22 can take a look at it #258

**Comment by ganhongyao** [comment]
> Hmm I just take a look at your PR and actually I have the same problem with testing charts. Perhaps @ganhongyao or @zhing22 can take a look at it #258

@leonghongfai @nbvannhi  May I know what's the issue with testing charts?

**Comment by leonghongfai** [comment]
> > Hmm I just take a look at your PR and actually I have the same problem with testing charts. Perhaps @ganhongyao or @zhing22 can take a look at it #258
> 
> @leonghongfai @nbvannhi May I know what's the issue with testing charts?

There seems to be an issue with doing studentstatistics.toLineChart() in the test file. Tldr I couldnt seem to generate a Chart object properly.

**Comment by zhing22** [comment]
oh no my problem. I'll try to fix it

**Comment by leonghongfai** [comment]
let me know if anyone is doing anything under student, if not i will finish them up probably by tmr mid aftn

**Comment by nbvannhi** [comment]
> 
> 
> let me know if anyone is doing anything under student, if not i will finish them up probably by tmr mid aftn

@leonghongfai I'm doing Assessment, AssessmentList and Score

**Comment by leonghongfai** [comment]
> > let me know if anyone is doing anything under student, if not i will finish them up probably by tmr mid aftn
> 
> @leonghongfai I'm doing Assessment, AssessmentList and Score

Okay noted!
