### ISSUE TITLE
Update DG

### ISSUE THREAD

**Issue by zhing22** [AY2122S1-CS2103T-W08-2/tp#249]
Acknowledgement:
- [x] code, ideas, libraries adapted

Design:
- [x] Architecture
- [x] UI
- [x] Model
- [x] Storage
- [x] Common

implementation: check your own parts if its still relevant + try to standardise
- [x] import
- [x] addstudent
- [x] addgroup (can please change the header `How the AddGroupCommand works:` so it dosent look weird in table of contents) (i changed the title alr)
- [x] addalloc
- [x] addscore
- [x] search
- [x] show

Appendix:requirements:
- [x] Product scope
- [x] user story
- [x] use case
- [x] non functional req (please help check)
- [x] glossary

Appendix:testing 
- [x] Saving Data (im not sure for the last case)

**Comment by nbvannhi** [comment]
I made some changes to the Table of Contents. What do yall think? Currently it looks like this

![image](https://user-images.githubusercontent.com/63232300/140604061-91db0394-9a4d-448a-854f-2f1874b35c2d.png)

If yall are okay with this then I can bold the titles of the UG too to make the DG and UG kinda consistent

**Comment by zhing22** [comment]
looks good! Can you add the subpoints under `Design` section too?

**Comment by nbvannhi** [comment]
> 
> 
> looks good! Can you add the subpoints under `Design` section too?

Ah okay!
